
MyNodeId = 15;

-- CONFIG CONFIG CONFIG CONFIG CONFIG CONFIG CONFIG
dofile "./docroot/DIST/config.lua"

-- WHITELISTED_FUNCTIONS WHITELISTED_FUNCTIONS WHITELISTED_FUNCTIONS
dofile "./docroot/DIST/whitelist.lua";

